### PR TITLE
Add Sprinting & Sneaking to Player

### PR DESCRIPTION
**Pull request by phase**
Add Sneaking & Sprinting booleans to the Player class.

### CODE REVIEW

**Comment by AgentTroll** [comment]
Upvote

**Comment by Phasesaber** [comment]
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project tridentsdk: Failed to deploy artifacts: Could not transfer artifact net.tridentsdk:tridentsdk:jar:1.0-20150320.064108-20 from/to tridentsdk-central (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/net/tridentsdk/tridentsdk/1.0-SNAPSHOT/tridentsdk-1.0-20150320.064108-20.jar. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]`
Um... wut? I don't think I did this... I hope I didn't do this...

**Comment by AgentTroll** [comment]
Server error with the repository.

**Comment by phase** [comment]
...

**Comment by phase** [comment]
Oops, the close button is right next to the comment button. :P

**Pull request closed without merging**
