### PR TITLE
Bars: BarType and BarReceiver

### PR DESCRIPTION
**Pull request by PizzaCrust**
This adds:

- BarReceiver interface
- BarType enum

A action bar looks like this:
Action Bar Image

A boss bar looks like this:
Boss Bar Image

### CODE REVIEW

**Comment by Vilsol** [comment]
I think you should remove the option of sending a bar with an id instead of enum, that already makes it harder to future-proof in case Mojang decides to mess something up.

**Comment by PizzaCrust** [comment]
Done.

**Comment by Vilsol** [comment]
Do you want to make a PR on Trident as well? With the actual implementation?

**Comment by PizzaCrust** [comment]
Sure, I'll implement this after this gets merged.

**Pull request merged**
