### PR TITLE
try-catching is expensive, use string/char stuff instead

### PR DESCRIPTION
**Pull request by hintss**

### CODE REVIEW

**Comment by Double0negative** [comment]
Try-Catching is only expensive if it throws an exception

**Comment by Double0negative** [comment]
Try-Catching is only expensive if it throws an exception

**Comment by hintss** [comment]
aka, it's expensive when people who never looked at how the method works in trident use it willy-nilly

**Comment by Double0negative** [comment]
Even if it catches, its still only expensive when it generates a stack trace, which this method doesn't

**Comment by AgentTroll** [comment]
Indeed, yes. While handling an exception is still added through the exception table in bytecode to be handled in the method call, the most overhead occurs inside printStackTrace, which does 3 iterations IIRC over the trace, line formatting, and if the trace happens to be very long (In essence, with netty), it will have a significant iteration time. However, because it isn't handled, it's not a problem.

**Pull request closed without merging**
