### PR TITLE
Little API Changes & Player Capabilities 

### PR DESCRIPTION
**Pull request by Phasesaber**
Changes to names and such, including Player sneaking & sprinting booleans.

### CODE REVIEW

**Comment by MazenMC** [comment]
Essentially, we have our naming conventions for a reason. Can you elaborate on why you made the change from `foo()` to `getFoo()`?

**Comment by Phasesaber** [comment]
@MazenMC I wasn't sure if it was a mistake or not. I haven't seen anyone use naming like that before. :P

**Comment by mythbusterma** [comment]
Java's Collections interface uses this naming convention.

**Comment by MazenMC** [comment]
Java 8's Stream API uses this convention, not forgetting [Objective-C's conventions state getters must have the same name as the property](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html#//apple_ref/doc/uid/TP40011210-CH10-SW3). "Unless specified otherwise, a getter method should use the same name as the property. For a property called firstName, the accessor method should also be called firstName. The exception to this rule is for Boolean properties, for which the getter method should start with is. For a property called paused, for example, the getter method should be called isPaused."

**Comment by Phasesaber** [comment]
@mythbusterma Hrm... Here's how I see it:
It's like a sentence. Your object is the subject, and your method is the predicate. 
`Phase.getPizza();` -> Phase gets pizza.
`Phase.pizza();` -> Phase pizza.

I'm not here to argue about that though, the main point was the Player changes. I'll change it back since Travis is yelling at me about it.

**Comment by MazenMC** [comment]
@Phasesaber It's worth noting that by what you are saying here, `getPizza` should invoke Phase to get a pizza, not return a property.

**Comment by Phasesaber** [comment]
@MazenMC But it's returning the pizza value from the object, aka getting it.

**Comment by Phasesaber** [comment]
And is there any reason to have the override in LivingEntity?

**Comment by Phasesaber** [comment]
Closing this because the one commit changed into ten. :P

**Comment by rowtn** [comment]
@Phasesaber Didn't anyone ever tell you about rebasing? : -^ )

**Comment by Phasesaber** [comment]
@rowtn No, I'll have to look into that later! :hurtrealbad:

**Pull request closed without merging**
