### PR TITLE
Titles: TitleReciever and TitleTransitions

### PR DESCRIPTION
**Pull request by PizzaCrust**
This adds:
- TitleReceiver interface
- TitleTransition class

### CODE REVIEW

**Comment by AgentTroll** [comment]
So here - what is a Title? Is it a display name? Scoreboard name? Meta tag? How will we implement this?

Otherwise, please refrain from using `@author <your name>`, as while we understand that crediting is important, contributor code submitted will be owned solely by TridentSDK in order to prevent individuals from taking down the entire codebase with a DMCA on say 1 line of code.

Please also add a COPYRIGHT header to your Title files, and place whitespace between the javadoc descriptor and the tags.

**Comment by mythbusterma** [comment]
That being said, you're more than welcome to also diff the Readme and add
yourself as a contributer.

**Comment by nallar** [comment]
> contributor code submitted will be owned solely by TridentSDK in order to prevent individuals from taking down the entire codebase with a DMCA on say 1 line of code.

Is there a contributor license agreement?

**Comment by PizzaCrust** [comment]
@AgentTroll Here's a picture of a title: https://i.ytimg.com/vi/6taEkAvR0BE/maxresdefault.jpg and placed the whitespace and and the copyright header. I have changed the @author tag to TridentSDK Team.

**Comment by AgentTroll** [comment]
@nallar In fact, there is, but I unfortunately don't own a copy of it. @mkotb can post it if you'd like to see it.

@PizzaCrust 
``` diff
+      * @param fadeIn the fade in time
 +     *
 +     * @param time the time of the title
 +     *
 +     * @param fadeOut the fade out time
```
this isn't correct, see [these lines](https://github.com/TridentSDK/Trident/blob/bleeding-edge/src/main/java/net/tridentsdk/server/concurrent/MainThread.java#L192-L194) for an example of what I'm talking about.

**Comment by PizzaCrust** [comment]
Fixed the whitespacing.

**Comment by AgentTroll** [comment]
Thank you for your contributions.

**Pull request merged**
